#!/bin/sh
# regenerate-decisions-index.sh
#
# Regenerate docs/decisions/INDEX.md from the D-NNN-*.md files in docs/decisions/.
#
# Usage:
#   scripts/regenerate-decisions-index.sh [decisions-dir]
#
# If [decisions-dir] is omitted, the script defaults to docs/decisions/
# relative to the current working directory.
#
# The script is idempotent: running it repeatedly produces the same INDEX.md
# given the same input files. It is POSIX sh compatible.
#
# It extracts the title from the first heading line ("# D-NNN: <title>") and
# the date from the first line matching "- **Date:** YYYY-MM-DD". Files that
# do not match the D-NNN-*.md pattern are ignored.

set -eu

DIR="${1:-docs/decisions}"

if [ ! -d "$DIR" ]; then
  mkdir -p "$DIR"
fi

INDEX="$DIR/INDEX.md"

# Write header
{
  echo "# Decision Index"
  echo ""
  echo "_Auto-generated by \`scripts/regenerate-decisions-index.sh\`. Do not edit by hand._"
  echo ""
  echo "| ID | Title | Date | File |"
  echo "|----|-------|------|------|"
} > "$INDEX"

# Walk decision files in lexical order (which is chronological for D-NNN naming)
# Use a portable glob; if no matches, the loop body is skipped.
found=0
for f in "$DIR"/D-*.md; do
  [ -e "$f" ] || continue
  found=1
  base="$(basename "$f" .md)"
  # Extract D-NNN prefix (everything up to the second hyphen-or-EOF after "D-")
  # Portable extraction: strip from first "-" after the prefix.
  id="$(printf '%s' "$base" | awk -F'-' '{ print $1 "-" $2 }')"

  # Title: first line starting with "# " — strip the leading "# "
  title="$(awk '/^# /{ sub(/^# /, ""); print; exit }' "$f")"
  if [ -z "$title" ]; then
    title="(untitled)"
  fi

  # Date: line matching "- **Date:** ..."
  date="$(awk -F'\\*\\*Date:\\*\\*' '/\*\*Date:\*\*/ { sub(/^[[:space:]]*/, "", $2); print $2; exit }' "$f")"
  if [ -z "$date" ]; then
    date="(unknown)"
  fi

  printf '| %s | %s | %s | [%s](./%s) |\n' "$id" "$title" "$date" "$base.md" "$base.md" >> "$INDEX"
done

if [ "$found" = "0" ]; then
  {
    echo ""
    echo "_No decisions recorded yet._"
  } >> "$INDEX"
fi

echo "Wrote $INDEX"
